### ISSUE TITLE
cluster problem

### ISSUE THREAD

**Issue by wumy27** [zhouyuangan/K-Means-Anchors#1]
This is my annotation path. But I find error when i run the cluster. Can any one help me?
![image](https://user-images.githubusercontent.com/46855459/84330320-b14af300-abb9-11ea-9c93-cb087bdc5695.png)

**Comment by yy9568** [comment]
@wumy27 please check your img_file is a valid path, if that's right, maybe your path contains Chinese words or other non-English words.
